# Generated by Django 6.1 on 2026-08-17 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_notes', to='opportunities.opportunity'),
        ),
    ]
